#!/bin/bash
# Quick Start Script for GraspNet with Pixel-to-Real Integration

echo "=========================================="
echo "GraspNet with Pixel-to-Real Quick Start"
echo "=========================================="
echo ""
echo "This script provides commands to start the vision pipeline"
echo "with pixel-to-world coordinate conversion."
echo ""
echo "REQUIRED: Run these commands in separate terminals"
echo ""

echo "Terminal 1: Start pixel_to_real service (REQUIRED FIRST)"
echo "-----------------------------------------------------------"
echo "cd ~/final_project_ws"
echo "source install/setup.bash"
echo "ros2 run vision pixel_to_real_service"
echo ""

echo "Terminal 2: Start SAM detector"
echo "-----------------------------------------------------------"
echo "cd ~/final_project_ws"
echo "source install/setup.bash"
echo "ros2 run vision simple_sam_detector"
echo ""

echo "Terminal 3: Start CLIP classifier"
echo "-----------------------------------------------------------"
echo "cd ~/final_project_ws"
echo "source install/setup.bash"
echo "ros2 run vision clip_classifier"
echo ""

echo "Terminal 4: Start GraspNet detector"
echo "-----------------------------------------------------------"
echo "cd ~/final_project_ws"
echo "source install/setup.bash"
echo "ros2 run vision graspnet_detector"
echo ""

echo "=========================================="
echo "TEST COMMANDS"
echo "=========================================="
echo ""

echo "1. Test pixel to world conversion (green box example)"
echo "-----------------------------------------------------------"
echo "ros2 service call /pixel_to_real custom_interfaces/srv/PixelToReal \"{u: 320, v: 240}\""
echo "Expected: x: 0.5, y: 0.0, z: 0.8"
echo ""

echo "2. Detect grasps for all objects"
echo "-----------------------------------------------------------"
echo "ros2 service call /vision/detect_grasp std_srvs/srv/Trigger"
echo ""

echo "3. Detect grasp in specific bounding box"
echo "-----------------------------------------------------------"
echo "ros2 service call /vision/detect_grasp_bb custom_interfaces/srv/DetectGraspBBox \"{x1: 250, y1: 180, x2: 390, y2: 300}\""
echo ""

echo "4. Run full pipeline (automatic with SAM)"
echo "-----------------------------------------------------------"
echo "ros2 service call /vision/run_pipeline std_srvs/srv/Trigger"
echo ""

echo "=========================================="
echo "KEY FEATURES"
echo "=========================================="
echo "✓ Grasp points detected in pixel coordinates (u, v)"
echo "✓ Converted to world coordinates (x, y, z) via /pixel_to_real"
echo "✓ quality_score: ALWAYS 0.1-1.0 (non-zero)"
echo "✓ grasp_width: ALWAYS ≥ 0.02m (non-zero)"
echo "✓ approach_angle: ALWAYS 30°-150° (non-zero)"
echo ""

echo "=========================================="
echo "CALIBRATION POINTS"
echo "=========================================="
echo "Pixel (320, 500) -> World (0.0, 0.0, 0.8)     [Origin]"
echo "Pixel (320, 240) -> World (0.5, 0.0, 0.8)     [Green Box]"
echo "Pixel (305,  95) -> World (0.83, 0.03, 0.8)   [Gear]"
echo "Pixel (466, 160) -> World (0.572, -0.241, 0.832) [Drill]"
echo "Pixel (150, 200) -> World (0.624, 0.373, 0.807)  [Wrench]"
echo ""

echo "For detailed documentation, see:"
echo "  - TEST_GRASP_WITH_PIXEL_TO_REAL.md"
echo "  - GRASP_PIXEL_TO_REAL_SUMMARY.md"
echo ""
