#!/usr/bin/env python3
"""
pixel_to_real_world.py
======================
Converts pixel (u,v) + depth to 3-D base-frame coordinates using a
**two-stage pipeline**:

  Stage 1 – Geometric model
    Apply calibrated camera intrinsics and extrinsics to produce an initial
    prediction (x_pred, y_pred) in the UR base frame.

  Stage 2 – Residual correction  (learned from calibration data)
    A 2nd-order polynomial is applied on top of the geometric prediction to
    remove systematic biases caused by camera tilt, extrinsic inaccuracy, and
    lens distortion.  Coefficients are loaded at startup from
    calibration/residual_correction.json (generated by
    calibration/geo_residual_calibrate.py).

    If no correction file is found the node falls back to geometric-only mode
    and logs a warning.

Correction feature vector
    F = [x_pred, y_pred, h, x_pred·y_pred, x_pred², y_pred², 1]
    x_final = x_pred + F @ coef_x
    y_final = y_pred + F @ coef_y

Service
    /pixel_to_real  (custom_interfaces/srv/PixelToReal)
    Request : int32 u, int32 v
    Response: float64 x, float64 y, float64 z   (metres, UR base frame)
"""

import json
import os

import numpy as np
import rclpy
from cv_bridge import CvBridge
from image_geometry import PinholeCameraModel
from rclpy.node import Node
from sensor_msgs.msg import CameraInfo, Image

from custom_interfaces.srv import PixelToReal


class PixelToRealNode(Node):

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def __init__(self):
        super().__init__("pixel_to_real_node")

        self.depth_sub = self.create_subscription(
            Image,
            "/camera/depth/image_rect_raw",
            self.depth_callback,
            10,
        )
        self.info_sub = self.create_subscription(
            CameraInfo,
            "/camera/color/camera_info",
            self.info_callback,
            10,
        )
        self.service = self.create_service(
            PixelToReal,
            "/pixel_to_real",
            self.handle_pixel_to_real,
        )

        self.bridge = CvBridge()
        self.cam_model = PinholeCameraModel()
        self.depth_image = None
        self.camera_ready = False

        # Depth scale: RealSense 16UC1 → metres
        self.depth_scale = 0.001

        # ---- Camera pose in UR base_link ----
        # t_base_cam : camera origin expressed in base frame  [x, y, height]
        # R_base_cam : rotation from camera frame to base frame
        #   Camera looking straight down →
        #     base_x =  cam_x,  base_y = –cam_y,  base_z = –cam_z
        self.t_base_cam = np.array([-0.109, 0.451, 0.66])
        self.R_base_cam = np.array([
            [1.0,  0.0,  0.0],
            [0.0, -1.0,  0.0],
            [0.0,  0.0, -1.0],
        ])

        # ---- Residual correction ----
        self._correction_loaded = False
        self._coef_x: np.ndarray | None = None
        self._coef_y: np.ndarray | None = None
        self._load_residual_correction()

        self.get_logger().info("PixelToRealNode ready (geometric + residual correction).")

    # ------------------------------------------------------------------
    # ROS callbacks
    # ------------------------------------------------------------------

    def depth_callback(self, msg: Image) -> None:
        self.depth_image = self.bridge.imgmsg_to_cv2(msg, "16UC1")

    def info_callback(self, msg: CameraInfo) -> None:
        self.cam_model.fromCameraInfo(msg)
        self.camera_ready = True

    # ------------------------------------------------------------------
    # Depth helpers
    # ------------------------------------------------------------------

    def get_robust_depth(self, u: int, v: int, window_size: int = 5):
        """Return median depth (raw 16-bit units) in a neighbourhood of (u,v)."""
        h_img, w_img = self.depth_image.shape
        half = window_size // 2

        u_min = max(u - half, 0)
        u_max = min(u + half + 1, w_img)
        v_min = max(v - half, 0)
        v_max = min(v + half + 1, h_img)

        window = self.depth_image[v_min:v_max, u_min:u_max]
        valid = window[window > 0]
        return None if len(valid) == 0 else float(np.median(valid))

    # ------------------------------------------------------------------
    # Residual correction
    # ------------------------------------------------------------------

    def _load_residual_correction(self) -> None:
        """
        Load polynomial residual correction coefficients from
        calibration/residual_correction.json (relative to this package root).
        Falls back to geometric-only mode if the file is absent.
        """
        script_dir = os.path.dirname(os.path.abspath(__file__))
        correction_path = os.path.normpath(
            os.path.join(script_dir, "..", "calibration", "residual_correction.json")
        )

        if not os.path.exists(correction_path):
            self.get_logger().warn(
                f"Residual correction file not found at:\n  {correction_path}\n"
                "  Running in geometric-only mode.  "
                "  Run calibration/geo_residual_calibrate.py to generate it."
            )
            return

        with open(correction_path, "r") as f:
            data = json.load(f)

        self._coef_x = np.array(data["coef_x"], dtype=np.float64)
        self._coef_y = np.array(data["coef_y"], dtype=np.float64)
        self._correction_loaded = True

        rms_before = data.get("rms_before_m", float("nan"))
        rms_after  = data.get("rms_after_m",  float("nan"))
        n_pts      = data.get("n_points", "?")

        self.get_logger().info(
            f"Residual correction loaded from:\n  {correction_path}\n"
            f"  Trained on {n_pts} points  |  "
            f"RMS {rms_before*1000:.1f} mm → {rms_after*1000:.1f} mm"
        )

    def _build_feature_vector(self, x_pred: float, y_pred: float, h: float) -> np.ndarray:
        """
        2nd-order polynomial feature vector.
        F = [x_pred, y_pred, h, x_pred*y_pred, x_pred², y_pred², 1]
        """
        return np.array([
            x_pred,
            y_pred,
            h,
            x_pred * y_pred,
            x_pred ** 2,
            y_pred ** 2,
            1.0,
        ], dtype=np.float64)

    def _apply_residual_correction(
        self, x_pred: float, y_pred: float, h: float
    ) -> tuple[float, float]:
        """
        Compute learned residual correction and return (dx, dy).
        x_final = x_pred + dx,  y_final = y_pred + dy.
        """
        F = self._build_feature_vector(x_pred, y_pred, h)
        dx = float(F @ self._coef_x)
        dy = float(F @ self._coef_y)
        return dx, dy

    # ------------------------------------------------------------------
    # Service handler
    # ------------------------------------------------------------------

    def handle_pixel_to_real(self, request, response):

        if self.depth_image is None or not self.camera_ready:
            self.get_logger().warn("Depth image or camera info not yet received.")
            return response

        u = request.u
        v = request.v

        depth_raw = self.get_robust_depth(u, v)
        if depth_raw is None:
            self.get_logger().warn(f"No valid depth near pixel ({u},{v}).")
            return response

        Z = depth_raw * self.depth_scale  # metres (distance along optical axis)

        # =================================================================
        # STAGE 1: Geometric model
        # -----------------------------------------------------------------
        # Use (u – cx)*Z/fx directly — this is the correct formulation that
        # avoids the subtle unit-vector scaling error that occurs when you
        # multiply a normalised direction ray by Z_depth.
        # =================================================================
        fx = self.cam_model.fx()
        fy = self.cam_model.fy()
        cx = self.cam_model.cx()
        cy = self.cam_model.cy()

        X_cam = (u - cx) * Z / fx
        Y_cam = (v - cy) * Z / fy
        Z_cam = Z

        p_cam  = np.array([X_cam, Y_cam, Z_cam])
        p_base = self.R_base_cam @ p_cam + self.t_base_cam

        x_pred = float(p_base[0])
        y_pred = float(p_base[1])
        z_pred = float(p_base[2])   # ≈ 0.0 for table-plane objects

        self.get_logger().debug(
            f"Geometric  ({u},{v}) → x={x_pred:.4f}  y={y_pred:.4f}  z={z_pred:.4f}"
        )

        # =================================================================
        # STAGE 2: Residual correction
        # -----------------------------------------------------------------
        # Polynomial model trained on (x_pred, y_pred, height) absorbs:
        #   • constant bias from extrinsic translation error
        #   • linear drift from camera tilt
        #   • quadratic / cross terms from lens distortion
        # =================================================================
        camera_height = float(self.t_base_cam[2])

        if self._correction_loaded:
            dx, dy = self._apply_residual_correction(x_pred, y_pred, camera_height)
            x_final = x_pred + dx
            y_final = y_pred + dy
            self.get_logger().debug(
                f"Correction dx={dx:+.4f}  dy={dy:+.4f}  "
                f"→ x={x_final:.4f}  y={y_final:.4f}"
            )
        else:
            x_final = x_pred
            y_final = y_pred

        response.x = x_final
        response.y = y_final
        response.z = z_pred

        return response


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(args=None):
    rclpy.init(args=args)
    node = PixelToRealNode()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
